# Generated by Django 4.2.7 on 2023-12-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="price",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
