# Generated by Django 4.2.7 on 2023-12-07 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_remove_category_price_category_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="categories",
        ),
    ]
