# Generated by Django 4.2.7 on 2023-12-07 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_rename_category_product_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
