name: Aplicação Python

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependências
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt  

    - name: Testar
      run: |
        python manage.py test
