name: Push Container to Fly.io

on:
  push:
    branches:
      - "main"

jobs:
  fly-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if flyctl is installed
        run: |
          echo "Checking if flyctl is installed..."
          if ! command -v flyctl &> /dev/null
          then
            echo "flyctl is not installed. Installing..."
            curl -L https://fly.io/install.sh | sh
            echo "flyctl installed successfully."
          else
            echo "flyctl is already installed."
          fi

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          export FLYCTL_CONFIG_FILE=/dev/null
          export FLY_ENV=remote

      - name: Login to Fly.io
        run: /home/runner/.fly/bin/flyctl auth login -t "${{ secrets.FLY_API_TOKEN }}"

      - name: Deploy to Fly.io
        run: /home/runner/.fly/bin/flyctl deploy
